on:
  push:
     branches: [master]
# Перечисление списка задач в данном workflow
jobs:
  # Задача тестирования
  test:
    # Название задачи
    name: Test code
    # Тип ВМ, на которой будет запущена задача
    runs-on: ubuntu-latest
    # Шаги выполняемые в рамках задачи
    steps:
        # Получаем код репозитория
      - name: Get code from repo
        uses: actions/checkout@v3
        # Устанавливаем python3.10
      - name: Set-up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        # Устанавливаем зависемости
      - name: Install dependencies
        run: pip install -r requirements.txt
        # Запускаем тесты
      - name: Run tests
        run: pytest
  # Задача развертывания
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
        # Настройка подключения по SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host yandex_server
            HostName ${{ secrets.HOST }}
            User ${{ secrets.LOGIN }}
            Port ${{ secrets.PORT }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
